language: go

install: true

go:
    - "1.x"
    - "1.8"
    - "1.10.x"

install:
    - get get -t -v ./...
script:
    - go test -cpu=1,2 -v -tags test ./...

notifications:
    email:
        on_success: change 
        on_failure: always
